config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # pages can manage the users model
  resources :pages do 
    resources :users
  end
  
  get '/signup', to: 'users#new', as: 'signup'

  resources :bookings
  resources :rooms

  # this route allow the user to create a new booking in the booking controoler
  get "bookings/:room/new", to: "bookings#new_booking", as: "new_room_booking"

  get "/rooms/:id", to: "rooms#shows"

  root 'pages#index'

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :user_id, :room_id, :check_in, :check_out, presence: true

  validate :room_availability

  # user can only display their bookings
  scope :by_user, -> (user) { where(user_id: user.id) }

  # define the rooms method for the Booking object
  def status
    room.room_status
  end

  def city
    room.room_city
  end

  def rooms
    room.room_address
  end

  # def fullname
  #   @user.full_name
  # end

  def guest_picture

  end

  private

  def room_availability
    # check if the room is available for the given time range
    overlapping_bookings = Booking.where(room_id: room_id).where.not(id: id).where(
    '(? <= check_out) AND (check_in <= ?)', check_in, check_out
    )

    # If there are any overlapping reservations, add an error
    if overlapping_bookings.any?
      errors.add(:base, "The room is not available for the selected dates.")
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    if params[:user] # if the user parameter is present and true
      @bookings = Booking.by_user(current_user) # show only the bookings of the current user
    else
      @bookings = Booking.all # show all the bookings
    end
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    # Initialize a new booking with the selected room and date
    @booking = Booking.new(room_id: params[:room_id], check_in: params[:check_in], check_out: params[:check_out])
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings/new
  def new_booking
    @room = Room.find(params[:room].to_i)
    @booking = Booking.new(room_id: @room.id)
    render :new
  end

  # POST /bookings or /bookings.json
  def create
    @room = Room.find_by(params[:room_id])

    if @room.owner == current_user
      flash[:alert] = "You cannot book your own room."
      redirect_to rooms_path

    elsif @room.coming_soon == "Coming soon" # check if the room its coming soon and prevent the booking
      flash[:alert] = "This room is coming soon and cannot be booked yet."
      redirect_to rooms_path

    else
      @booking = Booking.new(booking_params) # create a new booking with the submitted parameters
      @booking.user_id = current_user.id # assign the current user as the guest

      if @booking.save # save the booking and redirect to the confirmation page
        @booking.room.update(booked: true) # mark the room as booked
        redirect_to booking_path(@booking), notice: "Your booking was successfully created."

      else
        flash[:error] = 'Error creating booking!'
        render :new # render the new booking form with validation errors
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    # Find the booking by its id and destroy it
    @booking = Booking.find(params[:id])
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully cancelled." }
      format.json { head :no_content }
    end
  end

  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      if params[:id].present? && params[:id].to_i > 0
        @booking = Booking.find_by(params[:id])
      else
        redirect_to rooms_path, alert: "Invalid booking ID"
      end
    end

    # def set_booking
    #   @booking = Booking.find_by_id(params[:id])
    #   redirect_to bookings_path, alert: "Invalid booking ID" 
    #     unless @booking
    #   end
    # end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit( 
        :room_id, 
        :check_in, 
        :check_out
      )
    end

    # the method is in the booking model
    def overlapping_bookings?
      Booking.exists?(room_id: @room.room_id).where.not(id: params[:id]).where(
        '(? <= check_out) AND (check_in <= ?)', 
        booking_params[:check_in], booking_params[:check_out]
      )
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking.html.erb
<div id="new_booking" class="pages_index_background">
  <div id="<%= dom_id booking %>">
    <p>
      <strong>Check In:</strong>
      <%= booking.check_in %>
    </p>

    <p>
      <strong>Check Out:</strong>
      <%= booking.check_out %>
    </p>
  </div>
</div>

app/views/bookings/_deleteModal.html.erb
<div class="modal" id="<%= "myModal-#{booking.id}" %>">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header bg-info">
        <h4 class="modal-title">Are you sure?</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>

      <!-- Modal body -->
      <div class="modal-body bg-secondary">
      <p>Are you sure you want to delete the booked room <%= booking.room.room_address %>?</p>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer bg-outline-danger">
      <%= button_to("Delete", "/bookings/#{booking.id}", method: :delete, class: "btn btn-outline-danger", 
      data: { "bs-dismiss" => "modal" })  %>
      <button type="button", class="btn btn-outline-primary" data-bs-dismiss="modal">Cancel</button>         
      </div>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking, data: { turbo: false }) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 

  <div class="form-group">
    <div>
      <h5>Room address:</h5>
      <!-- display the full address in badge -->
      <span class="badge rounded-pill bg-success"> 
        <%= booking.room.room_address %>, <%= booking.room.room_city%>, <%= booking.room.room_state%> <%= booking.room.room_zip %>
      </span> 
    </div>

    <div>
      <%= form.label :check_in, style: "display: block" %>
      <%= form.date_field :check_in %>
    </div>

    <div>
      <%= form.label :check_out, style: "display: block" %>
      <%= form.date_field :check_out %>
    </div>
      
    <!-- creating hidden value for room id associated with booked room -->
    <%= form.hidden_field(:room_id, value: booking.room.id) %>

    <div style="margin-top: 20px;">
      <%= form.submit class:"btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<div id="new_booking" class="pages_index_background">
  <div class="container">
    <h1 id="editing_booking" class="display-4 text-center my-3 text-muted">Editing Booking</h1>

    <%= render "form", booking: @booking %>

    <br>

    <div>
      <%= link_to "Show this booking", @booking, class: "btn btn-outline-primary mb-5" %> 
      <%= link_to "Back to bookings", bookings_path, class: "btn btn-outline-primary mb-5" %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<!-- navbar for login page-->
<nav class="navbar navbar-info bg-info fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="#">
      <%= image_tag "logo_r4r-v01.png", class:"rounded float-start" %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-info" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">R4R offcanvas</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
              <%= link_to 'Logout', user_session_path(current_user), data: { turbo_method: :delete }, class: "dropdown-item" %><br>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Room
            </a>

            <ul class="dropdown-menu dropdown-menu-light">
              <%= link_to "List rooms", rooms_path, class: "dropdown-item" %>
              <%= link_to "Create room", new_room_path, class: "dropdown-item" %>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Booking
            </a>
            <ul class="dropdown-menu dropdown-menu-light">
              <%= link_to "List bookings", bookings_path, class: "dropdown-item" %>
            </ul>
          </li>
        </ul>
        <form class="d-flex mt-3" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </div>
</nav> <!-- /navbar for login page-->

<!-- banner component --> 
<section class="bsb-hero-5 px-3 bsb-overlay banner-background-image">
  <div class="container-fluid">
    <div class="row justify-content-md-center align-items-center">
      <div class="col-12 col-md-11 col-lg-9 col-xl-8 col-xxl-7">
        <h2 class="display-1 text-white text-center fw-bold mt-5" style="color: #3949AB">
          Welcome to R4R!
        </h2>
        <p class="lead text-white text-center mb-5 d-flex justify-content-sm-center">
          <span class="col-12 col-sm-10 col-md-8 col-xxl-7">Find your perfect room, make it your own!</span>
        </p>
      </div>
    </div>
  </div>
  </div>
</section>

<!-- filter the room based on the availability -->
<div class="container-fluid m-0" style="background-color: #dee2e6">
  <div>
    <div class="text-center my-0 text-muted">
      <%= form_tag(rooms_path, method: :get) do %>
        <%= label_tag(:check_in, "Check in:") %>
        <%= date_field_tag(:check_in) %>
        <%= label_tag(:check_out, "Check out:") %>
        <%= date_field_tag(:check_out) %>
        <%= submit_tag("Search for Room", class: "btn btn-outline-primary m-3") %>
      <% end %>
    </div>
  </div>
</div> <!-- /filter the room based on the availability -->

<h1 id="list_bookings" class="display-4 text-center my-3 text-muted">Booked Room(s)</h1>
<div class="container mt-3">
  <div class="row">
    <div class="col-lg table-responsive">
      <table class="table ml-2">
        <thead>
          <tr class="table-active">
            <th>Room Address</th>
            <th>City</th>
            <th>Check In</th>
            <th>Check Out</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @bookings.each do |booking| %> <!-- Loop through the bookings -->
            <tr>
              <td><%= booking.rooms %></td> <!-- rooms method allow the booking to access the room_address -->
              <td><%= booking.city  %></td> <!-- city method allow the booking to access the room_city -->
              <td><%= booking.check_in %></td> 
              <td><%= booking.check_out %></td>
              <td><%= button_to 'Show', booking, method: :get, class: 'btn btn-outline-primary' %></td>
            <!--<td><%= button_to 'Edit', edit_booking_path(booking), method: :get, class: 'btn btn-outline-success' %></td> 
              <td><button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#myModal-<%= booking.id %>">Delete</button></td> -->
            </tr>
            <%= render "deleteModal", booking: booking %>
          <% end %>
        </tbody>
      </table> 
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-4">
            <div class="row">
              <%= image_tag "Bedroom-1.jpg", class: "responsive" %>
            </div>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">Coming soon!</h5>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- footer-->
<footer class="bg-light text-lg-star fixed-bottom" style="background-color: gray; margin-top: 50px">
  <div class="text-center p-3">
    <p id="copyright" class="mb-2">© 2024 Muginga, Laurindo (Eli James) </p>
    <p>Find me on GitHub: <a href="https://github.com/muginga72"><i class="fab fa-github"></i></a></p>
    <p>Contact us: <a href="mailto:lmj.muginga@gmail.com"><i class="fas fa-envelope"></i></a></p>
  </div>
</footer>  <!-- footer-->

app/views/bookings/new.html.erb
<div id="new_booking" class="pages_index_background">
  <h1 class="display-4 text-center text-muted">New Booking</h1>

  <div class="container">
    <!-- to render booked room and pass also room instance -->
    <%= render "form", booking: @booking, room: @room %>

    <br>

    <div>
      <%= link_to "Back to bookings", bookings_path, class: "btn btn-outline-primary mb-4" %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>
<div id="new_booking" class="pages_index_background">
  <div class="container">
    <h1 id="editing_booking" class="display-4 text-center my-3 text-muted">Booking details</h1>

    <%= render @booking %>
    
    <div>
      <%= link_to "Edit this booking", edit_booking_path(@booking), class: "btn btn-outline-success mb-5" %> 
      <%= link_to "Back to bookings", bookings_path, class: "btn btn-outline-primary mb-5" %> <br>

      <%= button_to "Delete room", @booking, method: :delete, class: "btn btn-outline-danger", style: "margin-bottom: 20px;", data: { toggle: "modal", target: "#deleteModal" } %>
    </div>
  </div>
</div>